LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)

LOCAL_SRC_FILES:= \
	crc32.c \
	rawdata.c

LOCAL_STATIC_LIBRARIES := libc libcutils

LOCAL_FORCE_STATIC_EXECUTABLE := true
LOCAL_MODULE_PATH := $(TARGET_ROOT_OUT_BIN)
LOCAL_UNSTRIPPED_PATH := $(TARGET_ROOT_OUT_BIN_UNSTRIPPED)

LOCAL_MODULE := rawdatad
LOCAL_MODULE_TAGS := optional
include $(BUILD_EXECUTABLE)
